### ISSUE TITLE
Using live-nlu with models with Custom Components 

### ISSUE THREAD

**Issue by digitalWestie** [RasaHQ/rasalit#28]
I'm using Rasa 2.1.2, with the following pipeline in config:

```
pipeline:
  - name: SpacyNLP
    model: "en_core_web_sm"
  - name: SpacyTokenizer
  - name: custom_components.SimpleNameExtractor
  - name: SpacyEntityExtractor
    dimensions: ["PERSON"] #https://spacy.io/api/annotation#section-named-entities
  - name: SpacyFeaturizer
    pooling: mean
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
```

Running  `rasalit live-nlu` doesn't work since it doesn't know where to find `custom_components.SimpleNameExtractor`. I get the following error:

```
ComponentNotFoundException: Failed to load the component 'custom_components.SimpleNameExtractor'. Failed to find module 'custom_components'. Either your pipeline configuration contains an error or the module you are trying to import is broken (e.g. the module is trying to import a package that is not installed). Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/rasa/nlu/registry.py", line 121, in get_component_class return rasa.shared.utils.common.class_from_module_path(component_name) File "/usr/local/lib/python3.6/dist-packages/rasa/shared/utils/common.py", line 19, in class_from_module_path m = importlib.import_module(module_name) File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 994, in _gcd_import File "<frozen importlib._bootstrap>", line 971, in _find_and_load File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked ModuleNotFoundError: No module named 'custom_components'
```

Is there a way right now for me to point rasalit at my config or my custom class?
